 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Mohamed Ehab
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = {
                                             PORTA,PIN0,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTA,PIN1,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTA,PIN2,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTA,PIN3,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTA,PIN4,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTA,PIN5,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTA,PIN6,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTA,PIN7,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTB,PIN0,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTB,PIN1,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTB,PIN2,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTB,PIN3,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTB,PIN4,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTB,PIN5,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTB,PIN6,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTB,PIN7,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTC,PIN0,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTC,PIN1,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTC,PIN2,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTC,PIN3,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTC,PIN4,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTC,PIN5,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTC,PIN6,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTC,PIN7,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTD,PIN0,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTD,PIN1,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTD,PIN2,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTD,PIN3,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTD,PIN4,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTD,PIN5,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTD,PIN6,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTD,PIN7,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTE,PIN0,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTE,PIN1,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTE,PIN2,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTE,PIN3,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTE,PIN4,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTE,PIN5,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTF,PIN0,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORT_NUM_LED1,PIN_NUM_LED1,PORT_PIN_DIRECTION_LED1,PORT_INTERNAL_RESISTOR_LED1,PORT_PIN_LEVEL_VALUE_LED1,PORT_PIN_INITIAL_MODE_LED1,PORT_PIN_MODE_LED1,PORT_PIN_DIRECTION_CHANGEABLE_LED1,PORT_PIN_MODE_CHANGEABLE_LED1,
                                             PORTF,PIN2,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORTF,PIN3,PORT_PIN_IN,INTERNAL_RESISTOR_OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,DIRECTION_CHANGEABLE_OFF,MODE_CHANGEABLE_OFF,
                                             PORT_NUM_SW1,PIN_NUM_SW1,PORT_PIN_DIRECTION_SW1,PORT_INTERNAL_RESISTOR_SW1,PORT_PIN_LEVEL_VALUE_SW1,PORT_PIN_INITIAL_MODE_SW1,PORT_PIN_MODE_SW1,PORT_PIN_DIRECTION_CHANGEABLE_SW1,PORT_PIN_MODE_CHANGEABLE_SW1
                                         };



